[build]
  publish = "web/public"

[[redirects]]
  from = "/oauth/strava/*"
  to = "https://ibginimdnezoftxxygvt.functions.supabase.co/oauth-strava/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhooks/strava"
  to = "/.netlify/functions/strava-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/telegram/webhook/*"
  to = "/.netlify/functions/telegram-proxy/telegram/webhook/:splat"
  status = 200
  force = true


